# -*- coding: utf-8 -*-
"""GoogletranslateAPI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D3M1vH_np0eBeG9RvzBJHKgZWwl-BGkl
"""

# pip install googletrans==4.0.0rc1
import googletrans
from googletrans import Translator
import re
"""
#可翻譯的語言
print(googletrans.LANGUAGES)

#testing
translator = Translator()
text = "I want to rest"
#翻譯文字目前的語言
lang = translator.detect(text).lang
print(lang)

translated_text = translator.translate(text, src = lang, dest='en')
print(translated_text)
print(translated_text.text)
"""
def get_lang(text):
  if len(text) > 2000:
    text = text[:2000]
  translator = Translator()
  lang = translator.detect(text).lang

  return lang

def english_to_chinese(text):
  if len(text) > 2000:
    text = text[:2000]
  translator = Translator()
  lang = translator.detect(text).lang
  translated_text = translator.translate(text, src = lang, dest='zh-tw')
  return translated_text.text
"""
text = input('')
print(english_to_chinese(text))
"""

def chinese_to_english(text):
  if len(text) > 2000:
    text = text[:2000]
  translator = Translator()
  lang = translator.detect(text).lang
  translated_text = translator.translate(text, src = lang, dest='en')
  return translated_text.text
"""
text = input('')
print(chinese_to_english(text))
"""
